spring.application.name=event-booking


# Thay đổi thông tin theo database của bạn
spring.datasource.url=jdbc:postgresql://localhost:5432/event-booking
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Tự động cập nhật bảng từ code Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Với PostgreSQL ENUM type: JPA cần biết dùng STRING thay vì ORDINAL
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

# (Bổ sung) Dialect để Hibernate hiểu đúng cú pháp PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# JWT
app.jwt.secret=sdagfliasgfliasdgbyuagsdfiugawoirfgowgerosydofuiysodaigfsdohyfrow9e
app.jwt.access-token-expiration=900
app.jwt.refresh-token-expiration=2592000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


server.port=8088